server:
  port: 8080

spring:
  profiles:
    default: dev
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org.hibernate.SQL: debug
    org.hibernate.type : trace

